### ISSUE TITLE
Widget test error

### ISSUE THREAD

**Issue by arlakay** [fe-homecredit-id/flutter-direct#1]
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following StateError was thrown running a test:
Bad state: Too many elements

When the exception was thrown, this .....
The test description was:
  Login Screen
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (2) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: Login Screen

✖ Login Screen
Exited (1)

**Comment by dopefaceee** [comment]
issue is fixed on this [commit](https://github.com/fe-homecredit-id/flutter-direct/commit/951ab7e0a3de2d9634f5784d94b7870318d47fbb)
